before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: A/F6hSPxzjq53XPfr7QvhvzL6VEavpncsgRAsYPoVxMoFdJSFEuBHq1wrNVvkvHdQyBwuLxIqeVEUG00Inq+hCVD+gcUjafkKflJFr44JKl8Qavi8/gLiYuiTJuy+uBh3BCqqfLgZkgUPV71X3zZuusxw9ziLztH6xE9DAMG7c0FRVHz83EynIl4PGs/TOPIVYrpKx8dz8qGSkYM4juDM7rniWHGUQPNrZvvLBxZx9qHPO+H2G/c5TAa6ILk9gTuFKLb69hSzltlURP41icpU/bNm9OOmPa/tAog9DmX+dPKDD+NrEYt+f08swiAj+0of8pmQSYHlHviYsmdZHjaXLNmRIn0chjweT25WpiJSq6x+enqMlwpmTZrmKlsXgE8WrbaKDbTwiCZNYskMuUkAa+HVUDa00skKQYZijLziSPn5YcxqEzdkQrXh7j6Icdh8Im5r33AvpjcM/GLMtlX2Gl+AuOlSj7IROmbFv3WCzOi8u3HLFaiWiaM6MvgpgdgYNCBzpkjPejBi8LEe54C5mO8Wgc0QRS4FzLnbq1QCMszXMm2PfmBgmVYi/0pSaxv+7A6IFTD5fseAi8/Mh8Iyp6APHzNYcJ6+6r/fsHA4RHUjWG4blcrGzeQWmyPGqoPYI2fHyj6x+i2TvwUt+ZC1z5iImKqiytQw/uNYZgF7pk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
